### PR TITLE
Add utility to get the text within a textView or return null if there is...

### PR DESCRIPTION
**Pull request by smbarne**
... no text

### CODE REVIEW

**Comment by smbarne** [comment]
@dylanrjames pulled out the utility I wrote and added it to ViewUtils

**Comment by smbarne** [comment]
Note: if its good I'll take care of the rest of the submodule stuff.

**Comment by smbarne** [comment]
@dylanrjames should be good to go now.

**Comment by smbarne** [comment]
@dylanrjames updated javadoc with newlines, should be good now for real :]

**Comment by smbarne** [comment]
@dylanrjames I lied, now it is ready.  Learned about casting from CharSequence :/

**Comment by dylanrjames** [comment]
@smbarne  Derp, I missed that. I got too distracted by comments. Lol. Good catch.

**Pull request merged**
